pipeline {
    agent any
    tools {
            maven 'Maven3'
    }
    stages {
        stage('Build') {
            steps {
                   echo 'building process'
                   sh 'mvn -f user-service/pom.xml clean compile'
            }
        }
//         stage('Test') {
//             steps {
//                 echo 'test process'
//                 sh 'mvn clean test'
//             }
//         }
//         stage('Deploy') {
//             steps {
//                 //
//             }
//         }
    }
}