pipeline {
    agent any
    tools {
            maven 'Maven3'
    }
    stages {
        stage('Build') {
            steps {
                   echo 'building process'
                   sh 'mvn clean compile'
            }
        }
        stage('Test') {
            steps {
                echo 'test process'
                sh 'mvn test'
            }
        }
//         stage('Deploy') {
//             steps {
//                 //
//             }
//         }
    }
}