pipeline {
    agent any
    tools {
            maven 'Maven3'
    }
    stages {
            stage('Specify project location') {
                steps {
                       sh 'mvn compile'
                }
            }
//         stage('Build') {
//             steps {
//                    echo 'building process'
//                    sh 'mvn compile'
//             }
//         }
//         stage('Test') {
//             steps {
//                 echo 'test process'
//                 sh 'mvn clean test'
//             }
//         }
//         stage('Deploy') {
//             steps {
//                 //
//             }
//         }
    }
}